title: Research - Tufa Labs
heading: Research
email: info@tufalabs.com
description: >-
  Research blog for Tufa Labs, a small independent research group working on
  fundamental AI research, with a focus on o-style systems and post-training reasoning.
baseurl: "/blog"
url: "https://tufalabs.ai"
timezone: "Europe/Paris"
twitter_username: tufalabs
github_username: tufalabs

plugins:
  - jekyll-feed
  - jekyll-seo-tag
